apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-operator
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-operator
  template:
    metadata:
      labels:
        app: redis-operator
    spec:
      serviceAccountName: redis-operator
      containers:
        - name: operator
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
