apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: {{ .Values.name }}
  namespace: redis
spec:
  nodes: {{ .Values.nodes }}
  redisEnterpriseImageSpec:
    imagePullPolicy: IfNotPresent
    {{- if .Values.versionTag }}
    versionTag: {{ .Values.versionTag }}
    {{- end }}
  persistentSpec:
    enabled: true
