apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: {{ .Values.name }}
  namespace: redis
spec:
  nodes: {{ .Values.nodes }}
  {{- if .Values.redisEnterpriseVersion }}
  redisEnterpriseVersion: {{ .Values.redisEnterpriseVersion }}
  {{- end }}
  redisEnterpriseImageSpec:
    imagePullPolicy: IfNotPresent
  persistentSpec:
    enabled: true
