apiVersion: v1
kind: Secret
metadata:
  name: shared-db-secret
  namespace: redis
type: Opaque
stringData:
  username: admin
  password: mysecretpassword
---
apiVersion: v1
kind: Secret
metadata:
  name: shared-db-secret-2
  namespace: redis
type: Opaque
stringData:
  username: admin
  password: mysecretpassword2
