resources:
  - ../../base

configMapGenerator:
  - name: db-config
    literals:
      - memorySize=512mb
      - databasePort=12000
      - databaseSecretName=shared-db-secret

generatorOptions:
  disableNameSuffixHash: true