apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: db1
  namespace: redis
spec:
  memorySize: 512mb
  redisEnterpriseCluster:
    name: rec
  databaseSecretName: shared-db-secret
  databasePort: 12000
  shardCount: 1
  replication: false