apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alan-teodoro/poc-argocd
    targetRevision: HEAD
    path: overlays
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
