apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: redis
type: Opaque
stringData:
  token: hvs.CAESIBGF50vSCH3i1w9rNeDY4SpxPq94_WTbNsuGol09-MFpGh4KHGh2cy5KazRjOEJhUk8wR2VjYk1TcVR6STlXWmM