apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName }}
  namespace: redis
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.vaultSecretPath }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.vaultSecretPath }}
        property: password
