apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis-db-set
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  generators:
  - list:
      elements:
      - name: db1
        valueFile: overlays/db1/values.yaml
  template:
    metadata:
      name: redis-{{name}}
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/alan-teodoro/poc-argocd
        targetRevision: upgrade-test
        path: charts/redis-database
        helm:
          valueFiles:
          - '{{valueFile}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: redis
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

