apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: rec
spec:
  nodes: 1
  redisEnterpriseImageSpec:
    imagePullPolicy: Always
  uiServiceType: NodePort
  persistentSpec:
    enabled: false
  redisEnterpriseNodeResources:
    limits:
      memory: 4Gi
    requests:
      memory: 4Gi