apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: replace-me
spec:
  memorySize: replace-me
  databasePort: 0
  databaseSecretName: replace-me
  redisEnterpriseCluster:
    name: rec