apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: db2
  namespace: redis
spec:
  memorySize: 512mb
  databasePort: 12002
  redisEnterpriseCluster: 
    name: rec
  databaseSecretName: shared-db-secret