apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: db
  namespace: redis
spec:
  memorySize: 512mb
  databasePort: 12000
  redisEnterpriseCluster: 
    name: rec
  databaseSecretName: shared-db-secret