resources:
  - ../../base/redb.yaml

namePrefix: db2- # ou db2-

configMapGenerator:
  - name: db-config
    literals:
      - memorySize=512mb
      - databasePort=13000
      - databaseSecretName=shared-db-secret

replacements:
  - source:
      kind: ConfigMap
      name: db-config
      fieldPath: data.memorySize
    targets:
      - select:
          kind: RedisEnterpriseDatabase
        fieldPaths:
          - spec.memorySize
  - source:
      kind: ConfigMap
      name: db-config
      fieldPath: data.databasePort
    targets:
      - select:
          kind: RedisEnterpriseDatabase
        fieldPaths:
          - spec.databasePort
  - source:
      kind: ConfigMap
      name: db-config
      fieldPath: data.databaseSecretName
    targets:
      - select:
          kind: RedisEnterpriseDatabase
        fieldPaths:
          - spec.databaseSecretName

generatorOptions:
  disableNameSuffixHash: true
