resources:
  - ../../base

configMapGenerator:
  - name: db-config
    literals:
      - memorySize=1gb
      - databasePort=13000
      - databaseSecretName=shared-db-secret

generatorOptions:
  disableNameSuffixHash: true